// <auto-generated />
namespace winerack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class credentials_add_data1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(credentials_add_data1));
        
        string IMigrationMetadata.Id
        {
            get { return "201407260941516_credentials_add_data1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
