// <auto-generated />
namespace my.winerack.io.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class purchasenullableprice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(purchasenullableprice));
        
        string IMigrationMetadata.Id
        {
            get { return "201405240628200_purchase-nullable-price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
