// <auto-generated />
namespace winerack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class rename_tastings_to_openings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_tastings_to_openings));
        
        string IMigrationMetadata.Id
        {
            get { return "201407242349203_rename_tastings_to_openings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
