// <auto-generated />
namespace winerack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class wine_varietal_many_many : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wine_varietal_many_many));
        
        string IMigrationMetadata.Id
        {
            get { return "201503020031385_wine_varietal_many_many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
