// <auto-generated />
namespace winerack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_cellar_min_max_to_bottles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_cellar_min_max_to_bottles));
        
        string IMigrationMetadata.Id
        {
            get { return "201407130442121_add_cellar_min_max_to_bottles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
