// <auto-generated />
namespace winerack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class wine_activities_cascade_delete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wine_activities_cascade_delete));
        
        string IMigrationMetadata.Id
        {
            get { return "201503022329303_wine_activities_cascade_delete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
