// <auto-generated />
namespace winerack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class add_opening_rating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_opening_rating));
        
        string IMigrationMetadata.Id
        {
            get { return "201503300447459_add_opening_rating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
